language: python
dist: xenial
sudo: false

services:
  - xvfb

addons:
    apt:
      packages:
        - herbstluftwm
        - libxkbcommon-x11-0

env:
   global:
      - OFFICIAL_REPO="pcdshub/qtpyinheritance"
      # Doctr deploy key for pcdshub/qtpyinheritance
      - secure: ""

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env:
        - CONDA_UPLOAD=1
        - BUILD_DOCS=1
        - QT_API=pyqt5
    - python: 3.7
      env:
        - QT_API=pyqt5
    - python: 3.6
      env:
        - QT_API=PySide2
    - python: 3.7
      env:
        - QT_API=PySide2

install:
  # Install requirements
  - pip install -Ur requirements.txt
  # Install additional development requirements
  - pip install -Ur dev-requirements.txt
  # Install the package
  - pip install -e .
  # Install the specific binding we're testing against
  - pip install "${QT_API}"


before_script:
  # Run the window manager
  - "herbstluftwm &"
  - sleep 1


script:
  - flake8 qtpyinheritance
  - export PYTEST_QT_API="${QT_API}"
  - coverage run run_tests.py
  - set -e

  - |
    if [[ "$BUILD_DOCS" == "1" ]]; then
      # Create HTML documentation
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages --command "touch .nojekyll; git add .nojekyll"
    fi


after_success:
  - coverage report -m
